# Generated by Django 5.2.12 on 2026-04-03 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_kg_saved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_value_saved', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_verifications', models.IntegerField(default=0)),
                ('total_matches', models.IntegerField(default=0)),
                ('total_donors', models.IntegerField(default=0)),
                ('total_charities', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Impact metrics',
            },
        ),
        migrations.CreateModel(
            name='DemandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('cooked_meals', 'Cooked Meals'), ('raw_vegetables', 'Raw Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy Products'), ('bakery', 'Bakery Items'), ('packaged', 'Packaged Food'), ('beverages', 'Beverages'), ('mixed', 'Mixed / Other')], max_length=20)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Demand histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FoodListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_type', models.CharField(choices=[('cooked_meals', 'Cooked Meals'), ('raw_vegetables', 'Raw Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy Products'), ('bakery', 'Bakery Items'), ('packaged', 'Packaged Food'), ('beverages', 'Beverages'), ('mixed', 'Mixed / Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expiry_time', models.DateTimeField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('matched', 'Matched'), ('picked_up', 'Picked Up'), ('verified', 'Verified'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='available', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance_km', models.FloatField(default=0, help_text='Haversine distance')),
                ('road_distance_km', models.FloatField(default=0, help_text='OSRM road distance')),
                ('need_score', models.FloatField(default=0, help_text='ML-predicted need score 0.0–1.0')),
                ('match_score', models.FloatField(default=0, help_text='Composite matching score')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('picked_up', 'Picked Up'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('delivery_photo', models.ImageField(blank=True, null=True, upload_to='delivery_photos/')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_matches', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.foodlisting')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('donor', 'Donor'), ('charity', 'Charity'), ('admin', 'Admin')], default='donor', max_length=10)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField(default=12.9716)),
                ('longitude', models.FloatField(default=77.5946)),
                ('address', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
