# Generated by Django 5.2.12 on 2026-05-17 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes from admin review'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_doc',
            field=models.FileField(blank=True, help_text='Legal/license document for verification', null=True, upload_to='registration_docs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
